#!/usr/bin/python3
# Automatically generated by Pynguin.
import unittest
from .path import src as module_0


class TestTriangle(unittest.TestCase):

    def test_case_0(self):
        int_0 = -1826
        int_1 = -1938
        str_0 = module_0.triangle(int_0, int_0, int_1)
        assert str_0 == 'Isosceles triangle'


    def test_case_1(self):
        int_0 = 1088
        int_1 = None
        str_0 = module_0.triangle(int_0, int_1, int_1)
        assert str_0 == 'Isosceles triangle'


    def test_case_2(self):
        int_0 = 2612
        str_0 = module_0.triangle(int_0, int_0, int_0)
        assert str_0 == 'Equilateral triangle'
        int_1 = -5394
        int_2 = -92
        int_3 = -1524
        str_1 = module_0.triangle(int_1, int_2, int_3)
        assert str_1 == 'Scalene triangle'


    def test_case_3(self):
        #int_0 = -3481
        int_0 = - -34811203230857123485
        int_1 = -2574
        str_0 = module_0.triangle(int_0, int_1, int_0)
        assert str_0 == 'Isosceles triangle'


    def test_case_4(self):
        #int_0 = -1896
        int_0 = -348111111111111111
        int_1 = -2267
        int_2 = -808
        str_0 = module_0.triangle(int_0, int_1, int_2)
        assert str_0 == 'Scalene triangle'
        print("Hello")
