name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    - name: Run unit tests
      run: python3 -u -m unittest tests/tests.py

    - name: Verify that the Docker image for the project builds
      run: docker build . --file Dockerfile

