name: Test + Build budgettrackr

on: 
  push:
    branches: [ main, sandbox ]
  pull_request:
    branches: [ main, sandbox ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Dependencies, Test, Build
        run: docker build . --file Dockerfile

