name: Setup Python Dependencies

on:
  push:
    branches: [ main, sandbox ]
  pull_request:
    branches: [ main, sandbox ]

jobs:
  PythonDependcencies:
    name: Setup Python Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

        with:
          python-version: '3.x'
          cache: 'pip' 
          run: pip install -r requirements.txt

