name: Python Linting

on: 
  push:
    branches: [ main, sandbox ]
  pull_request:
    branches: [ main, sandbox ]

jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Konstruktoid Python linting
        uses: konstruktoid/action-pylint@master

