name: Unit Tests

on: 
  push:
    branches: [ main, sandbox ]
  pull_request:
    branches: [ main, sandbox ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Format with Autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --recursive --in-place --aggressive --aggressive .

      - name: Run Unit Tests
        uses: onichandame/python-test-action@master
        with:
          deps_list: 'requirements.txt'

